### ISSUE TITLE
bug when running

### ISSUE THREAD

**Issue by zx000523** [linomi/fuzzyDWA#1]
when running betaa = beta_rule(fis_input), there is TypeError: unsupported operand type(s) for *: 'method' and 'float'

**Comment by linomi** [comment]
Sorry for my late response!
It's just a dependency problem, I think you are using the latest version of fuzzylogic package, I wrote this code several years ago, so to resolve your issue just uninstall fuzzylogic package by running this code in your terminal: 
`pip uninstall fuzzylogic`
and then install the older version: 
`pip install fuzzylogic==1.2.0`
. let me know if you have any other question.
PS: there are dozens of lines just for the purpose of visualization, if you don't need them, you can simply get rid of them
Have fun

**Comment by zx000523** [comment]
Thank you so much for your response and for providing the solution!
I really appreciate you taking the time to help me resolve this issue.Also, thanks for the tip about the visualization lines. I’ll keep that in mind.
Thanks again and have a great day!
